# Generated by Django 5.0.3 on 2024-03-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leitor',
            name='autor',
        ),
        migrations.AlterField(
            model_name='leitor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Leitor'),
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Livro')),
                ('preco', models.IntegerField(verbose_name='Preço do Livro')),
                ('data_plub', models.DateField(verbose_name='Status do Livro')),
                ('status', models.BooleanField(verbose_name='Status do livro')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.autor', verbose_name='Autor do Livro')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.editora', verbose_name='Editora do Livro')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero', verbose_name='Genero do Livro')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
