# Generated by Django 5.0.3 on 2024-03-18 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='emprestimo',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='datadevolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Devolução'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='dataemprestimo',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emprestimo'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='leitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.leitor', verbose_name='Leitor'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.livro', verbose_name='Livro'),
        ),
    ]
